# Generated by Django 6.0.4 on 2026-04-27 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Aeroport nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Aeroport kodi (masalan, TAS)')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Aeroport',
                'verbose_name_plural': 'Aeroportlar',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Pasport raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': "Yo'lovchi",
                'verbose_name_plural': "Yo'lovchilar",
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='Reys raqami')),
                ('departure_time', models.DateTimeField(verbose_name='Uchish vaqti')),
                ('arrival_time', models.DateTimeField(verbose_name="Qo'nish vaqti")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chipta narxi ($)')),
                ('total_seats', models.PositiveIntegerField(default=150, verbose_name="Umumiy o'rindiqlar soni")),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='chipta.airport', verbose_name="Qo'nish aeroporti")),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='chipta.airport', verbose_name='Uchish aeroporti')),
            ],
            options={
                'verbose_name': 'Reys',
                'verbose_name_plural': 'Reyslar',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name="O'rindiq raqami")),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Bron qilingan sana')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda (Bron qilingan)'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='chipta.flight', verbose_name='Reys')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chipta.passenger', verbose_name="Yo'lovchi")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Foydalanuvchi (Sayt a'zosi)")),
            ],
            options={
                'verbose_name': 'Chipta',
                'verbose_name_plural': 'Chiptalar',
            },
        ),
    ]
